### ISSUE TITLE
is there a workaround for when a kernel config is not present?

### ISSUE THREAD

**Issue by vinnie357** [alexeadem/qbo-home#1]
https://github.com/alexeadem/qbo-home/blob/e0567e78563e0f73eef1b3f98143da9055d5b044/qbo#L23

I was trying out the command in a github codespace with docker. ubuntu 20.x
```
uname -r 
5.4.0-1090-azure
```

```error
 $ ./qbo start api
  => start api
clean = 0
OS = Linux
warning: start does not exist, searching other paths for kernel config ...: 
error: cannot find kernel config: 
  try running this script again, specifying the kernel config:: 
    CONFIG=/path/to/kernel/.config ./qbo or ./qbo /path/to/kernel/.config: 
  ```

**Comment by alexeadem** [comment]
You can comment  the line with `run_linux_tests` in the script.

https://github.com/alexeadem/qbo-home#linux

 It is just checking cgroups version and limits on `max_user_watches` and `max_user_instances` You can modify these manually if needed as indicated here:

https://github.com/alexeadem/qbo-home/blob/e0567e78563e0f73eef1b3f98143da9055d5b044/qbo#L330

**Comment by alexeadem** [comment]
is it worth adding a helper to run/parse sysctl outputs? for your test? 

> Yes that would be useful. Those are the only two systcl values to consider. The only limitation if those values are low is that you'll be limited on the number of nodes you can run.

For more info:

https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files

The other test is to verify that you have Cgroups v1.

**Comment by alexeadem** [comment]
Let me know if that works. Closing the issue.
